/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.proyecto.view;

import java.awt.event.ActionListener;

/**
 *
 * @author RYZEN
 */
public class LevelFrame extends javax.swing.JFrame {

    int xClick, yClick;
    
    public LevelFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void listen(ActionListener controller) {
        btnRegresar.addActionListener(controller);
        btnlevel1.addActionListener(controller);
        btnlevel2.addActionListener(controller);
        btnlevel3.addActionListener(controller);
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnlevel1 = new javax.swing.JButton();
        btnlevel2 = new javax.swing.JButton();
        btnlevel3 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        arrastre = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlevel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/level1icon.png"))); // NOI18N
        btnlevel1.setActionCommand("LEVEL1");
        btnlevel1.setBorder(null);
        btnlevel1.setBorderPainted(false);
        btnlevel1.setContentAreaFilled(false);
        btnlevel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlevel1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnlevel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        btnlevel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/level2icon.png"))); // NOI18N
        btnlevel2.setActionCommand("LEVEL2");
        btnlevel2.setBorder(null);
        btnlevel2.setBorderPainted(false);
        btnlevel2.setContentAreaFilled(false);
        btnlevel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlevel2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnlevel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        btnlevel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/level3icon.png"))); // NOI18N
        btnlevel3.setActionCommand("LEVEL3");
        btnlevel3.setBorder(null);
        btnlevel3.setBorderPainted(false);
        btnlevel3.setContentAreaFilled(false);
        btnlevel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlevel3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnlevel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRegreso.png"))); // NOI18N
        btnRegresar.setActionCommand("REGRESAR");
        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 640, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/levelFrame.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        arrastre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                arrastreMouseDragged(evt);
            }
        });
        arrastre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                arrastreMousePressed(evt);
            }
        });

        javax.swing.GroupLayout arrastreLayout = new javax.swing.GroupLayout(arrastre);
        arrastre.setLayout(arrastreLayout);
        arrastreLayout.setHorizontalGroup(
            arrastreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        arrastreLayout.setVerticalGroup(
            arrastreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(arrastre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arrastreMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrastreMouseDragged
        this.setLocation(evt.getXOnScreen() - xClick, evt.getYOnScreen() - yClick);
    }//GEN-LAST:event_arrastreMouseDragged

    private void arrastreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrastreMousePressed
        xClick = evt.getX();
        yClick = evt.getY();
    }//GEN-LAST:event_arrastreMousePressed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnlevel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlevel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlevel1ActionPerformed

    private void btnlevel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlevel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlevel2ActionPerformed

    private void btnlevel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlevel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlevel3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LevelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LevelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LevelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LevelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LevelFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel arrastre;
    public javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnlevel1;
    public javax.swing.JButton btnlevel2;
    public javax.swing.JButton btnlevel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
